import { Game } from "@/components/game-card"
import Badge from "@/components/ui/badge"
import Button from "@/components/ui/button"
import YouTubeVideo from "@/components/ui/youtube-video"
import { Heart, ShoppingCart, User } from "lucide-react"
import { Metadata } from "next"

export async function generateMetadata({
  params,
}: {
  params: { id: string | number }
}): Promise<Metadata> {
  const { id } = params
  return {
    title: `${id} on Steam`,
    description: "Generated by create next app",
  }
}

export default async function GamePage({
  params,
}: {
  params: Promise<{ id: string | number }>
}) {
  const { id } = await params

  const game: Game = await fetch(`http://localhost:4321/api/games/${id}`).then(
    (res) => res.json()
  )

  // TODO call the api to fetch the game data and make a loading.ts page inside this route

  return (
    <main className="flex flex-col min-h-screen items-center rounded-lg pb-20 sm:py-10 bg-gradient-to-b from-header to-primary/30">
      <div className="max-w-5xl mx-auto">
        <header className="flex justify-between w-full items-center mb-8">
          <h1 className="text-4xl font-bold">{game.name}</h1>
          <Button>
            Whislist <Heart size={16} />
          </Button>
        </header>
        <main className="grid grid-cols-5 gap-8 mb-8">
          <section className="col-span-3">
            <YouTubeVideo videoId={game.trailer} />
            <footer className="flex justify-between items-center gap-4 mt-4 bg-card p-4 rounded-lg">
              <div>
                <p className="font-semibold">{game.name}</p>
                <p className="text-secondary text-sm">
                  Special offer ends in 19 October
                </p>
              </div>
              <div className="flex items-center gap-4">
                <span className="bg-accent text-header p-2 rounded-lg font-bold">
                  -{game.discount}%
                </span>
                <div className="flex flex-col font-semibold">
                  <span className="line-through text-foreground/60">
                    ${game.price}
                  </span>
                  <span color="text-accent">${game.price - game.discount}</span>
                </div>
                <Button>
                  Add to cart <ShoppingCart size={18} />
                </Button>
              </div>
            </footer>
            <footer className="gap-4 mt-4 bg-card p-4 rounded-lg space-y-4">
              <div className="flex justify-between items-center">
                <div>
                  <p className="font-semibold">
                    Super Mario Odyssey Deluxe Edition
                  </p>
                  <p className="text-secondary text-sm">
                    Special offer ends in 19 October
                  </p>
                </div>
                <div className="flex items-center gap-4">
                  <span className="bg-accent text-header p-2 rounded-lg font-bold">
                    -55%
                  </span>
                  <div className="flex flex-col font-semibold">
                    <span className="line-through text-foreground/60">
                      $89.99
                    </span>
                    <span color="text-accent">$50.99</span>
                  </div>
                  <Button>
                    Add to cart <ShoppingCart size={18} />
                  </Button>
                </div>
              </div>
              <div className="p-4 rounded-lg bg-header text-sm">
                <p className="text-foreground/60">Includes</p>
                <ul>
                  <li>Super Mario Odyssey</li>
                  <li>Super Mario Odyssey Artbook</li>
                  <li>Super Mario Odyssey BSO</li>
                </ul>
              </div>
            </footer>
            <section className="bg-card p-4 rounded-lg mt-4">
              <h4 className="font-semibold text-xl mb-2">About {game.name}</h4>
              <p className="text-sm text-foreground">{game.about}</p>
            </section>
          </section>
          <section className="col-span-2">
            <img className="rounded-lg mb-4" src={game.poster} />
            <p className="mb-4">{game.description}</p>
            <span className="bg-green-500 text-header rounded-lg px-3 py-1 text-sm font-semibold shadow">
              {game.rating} | {game.total_reviews}
            </span>
            <p className="text-foreground/60 my-4">
              Release Date
              <span className="text-secondary pl-2">{game.released}</span>
            </p>
            <p className="text-foreground/60 my-4">
              Developer
              <span>
                <span className="text-secondary pl-2">{game.developer}</span>
              </span>
            </p>
            <p className="text-foreground/60 my-4">
              Publisher
              <span>
                <span className="text-secondary pl-2">{game.publisher}</span>
              </span>
            </p>
            <h4 className="text-foreground/60">Popular tags</h4>
            <div className="flex flex-wrap gap-2 mt-2">
              {game.tags.map((tag) => (
                <Badge key={tag}>{tag}</Badge>
              ))}
            </div>
            <section className="bg-card p-4 rounded-lg mt-4">
              <h4 className="text-foreground/60 mb-2">Features</h4>
              <ul className="flex flex-col gap-2">
                {game.features.map((feature) => (
                  <li
                    className="flex items-center gap-2 text-secondary bg-header p-2 rounded-lg"
                    key={feature}
                  >
                    <User size={16} /> {feature}
                  </li>
                ))}
              </ul>
            </section>
            <section className="bg-card p-4 rounded-lg mt-4">
              <h4 className="text-foreground/60 mb-2">Languages</h4>
              <ul className="flex flex-col gap-2">
                {game.languages.map((language) => (
                  <li
                    className="flex items-center gap-2 text-secondary bg-header p-2 rounded-lg"
                    key={language}
                  >
                    <User size={16} /> {language}
                  </li>
                ))}
              </ul>
            </section>
          </section>
        </main>
        <section>
          <h2 className="text-xl font-bold mb-4">Related Games</h2>
          <div className="flex flex-wrap gap-4 max-w-4xl items-center"></div>
        </section>
      </div>
    </main>
  )
}
