import { Metadata } from "next"

export async function generateMetadata({
  params,
}: {
  params: { id: string | number }
}): Promise<Metadata> {
  const { id } = params
  return {
    title: `${id} on Steam`,
    description: "Generated by create next app",
  }
}

export default async function GamePage({
  params,
}: {
  params: Promise<{ id: string | number }>
}) {
  const { id } = await params

  // TODO call the api to fetch the game data and make a loading.ts page inside this route

  return <div>Game Page {id}</div>
}
